### PR TITLE
March 2019 wds updates

### PR DESCRIPTION
**Pull request by kylebunting**
Fixed hosting location of web sites and APIs.

### CODE REVIEW

**Comment by waltermyersiii** [comment]
Looks good. Ready for SME review.

**Comment by ccompy** [comment]
The training changed from going from Web Apps to containers to going from VMs in Azure to containers which is good to change it from web apps but, it still should not be from another Azure service.  
Our workshop goal should be around getting customers to move from on-premises or from a competitor to Azure.  There is a problem in that it makes the source service appear inadequate in some manner. That is fine with a competitor or on-premises but less so when the source is another Azure service.

**Comment by waltermyersiii** [comment]
Thanks, Christina. My request was exactly as you stated, but I thought VMs was viable as well. I will setup some time to talk with Kyle.

**Comment by ccompy** [comment]
Also, I know there isn't time for it right now, but really the workshop goal ought to be more around how to pick the right service for the problem, not just send them to AKS. AKS is not the only solution nor the best for everything. The challenge I hear over and over from customers is how to know which service to use.  If we just send everybody to AKS then we just confuse customers. I see customers try it, then leave it.  It reminds me of how the field sent customers to ASE for everything for a while.  Right tool for the right job.

**Comment by waltermyersiii** [comment]
I agree, Christina. We're going to look at precisely that next update. I see App Service as a solution to this also.

**Pull request merged**
