### PR TITLE
Update for fixing Issues with Azure DevOps Authentication

### PR DESCRIPTION
**Pull request by PraveenAnil**
This Commit includes fixes for:

1.  Starter file was getting extracted to FabMedical folder within another Fabmedical
2.  Authentication Issues for Azure DevOps Git
3.  Unable to execute Exercise 2 -> Task 2 -> Step 12 as clip.exe was not found in WSL.

### CODE REVIEW

**Comment by jamesrcounts** [comment]
LGTM

**Comment by alpinstang** [comment]
Tested and working.

**Comment by jamesrcounts** [comment]
@DawnmarieDesJardins looks like this is good to go.

**Comment by DawnmarieDesJardins** [comment]
PR merged & HTML files updated.

**Pull request merged**
