### PR TITLE
fixing ingress path rewrite rule

### PR DESCRIPTION
**Pull request by kevinhillinger**
Without this update, the static content (CSS, images) won't render.

### CODE REVIEW

**Comment by kevinhillinger** [comment]
If this doesn't get fixed, the participant will experience failure during the lab.

**Comment by DawnmarieDesJardins** [comment]
@kevinhillinger 
Thanks Kevin!  I've reached out to our authors for to review.  Dawnmarie

**Comment by jamesrcounts** [comment]
This looks fine.  

Please note that the lab never asks the student to visit the web site after configuring ingress, only the API, so students should not be encountering this issue unless they are experimenting outside the lab's stated instructions.

Thanks Kevin!

**Comment by lastcoolnameleft** [comment]
Hey everyone,

I made an oops and accidentally committed the FabMedical files into the master repo. 
 https://github.com/microsoft/MCW-Containers-and-DevOps/commit/e669a41956d0b77ec658591eea6da8b29e65c986

I've rebased to remove that commit; however, because the generated SHA1 has been changed, the parent commit has changed.

That said, I've gone ahead and verified that the master branch has not lost any commits.  I apologize for any inconvenience.

https://github.com/microsoft/MCW-Containers-and-DevOps/commit/7ca04ff7d9db78894a0c4892034cebbc4c434d33

TL;DR:  This PR might not show the same parent SHA1; however, I have verified that the commits are definitely there.

**Pull request merged**
