### PR TITLE
March 2019 update

### PR DESCRIPTION
**Pull request by jamesrcounts**
For #66

### CODE REVIEW

**Comment by dmckinstry** [comment]
I would love to see compliant branding used in the whiteboard session per #84.  (Sorry - I just added this Issue.)  I'll skim the rest of the PR.

**Comment by keikhara** [comment]
Hi can we add information on how to monitor the deployments and AKS? thanks,

**Comment by waltermyersiii** [comment]
Absolutely. I believe that's in the plan for the May update to the labs.

**Comment by waltermyersiii** [comment]
Jim, please get rid of references "on premise" or "on premises" and make consistently "on-premises."

**Comment by DawnmarieDesJardins** [comment]
@jamesrcounts @ZoinerTejada 
Hello!
SME review is closed for this update.  Please finalize the changes, close open issues that have been addressed in this update and assign it to me when it's ready for QC/Merge.
Thanks, Dawnmarie

**Pull request merged**
