### PR TITLE
September update

### PR DESCRIPTION
**Pull request by jamesrcounts**
For #104

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
When finalizing this workshop, the correct naming convention for the new title is: Cloud-native applications.  Thank you!

**Comment by waltermyersiii** [comment]
@jamesrcounts I don't see anything in the WDS that discusses the shift away from Windows Server to Linux. It's important to note that the shift to Linux will provide for small footprint containers that will enjoy greater density for their web applications. Lower cost as well.

**Comment by waltermyersiii** [comment]
In Task 6 of Before HOL, I don't see CosmosDB entries in parameters file.

**Comment by jamesrcounts** [comment]
> In Task 6 of Before HOL, I don't see CosmosDB entries in parameters file.

@waltermyersiii, I'm not sure whats going on here.  I see the updates in the diff view for this PR:

[Hands-on lab/arm/azuredeploy.parameters.json](https://github.com/microsoft/MCW-Containers-and-DevOps/pull/109/files?file-filters%5B%5D=.json&file-filters%5B%5D=.yaml&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension&file-filters%5B%5D=dotfile#diff-6d109c94cccab37e06daf7a316123572):

**Comment by jamesrcounts** [comment]
> @jamesrcounts I don't see anything in the WDS that discusses the shift away from Windows Server to Linux. It's important to note that the shift to Linux will provide for small footprint containers that will enjoy greater density for their web applications. Lower cost as well.

@waltermyersiii Is this something new you want us to find a place for or did I lose track of this ask?

**Comment by jamesrcounts** [comment]
> When finalizing this workshop, the correct naming convention for the new title is: Cloud-native applications. Thank you!

This should be done now

**Comment by waltermyersiii** [comment]
Thanks for adding instructions, @jamesrcounts. I was able to deploy in my MSDN account using a directory I created.

**Pull request merged**
