### PR TITLE
Update HOL unguided - Containers and DevOps.md

### PR DESCRIPTION
**Pull request by msaravindh**

### CODE REVIEW

**Comment by waltermyersiii** [comment]
Hi msaravindh. Who are you? We have a PR through from the vendor, so would like to apply this afterwards.

**Comment by waltermyersiii** [comment]
@jstulo, how was this not caught earlier?

**Comment by jstulo** [comment]
Apologies. I did encounter that but it seems I failed to fix the typo in the docs.

**Comment by msaravindh** [comment]
>           Hi msaravindh. Who are you? We have a PR through from the vendor, so would like to apply this afterwards.

Hi Walter. Just a Microsoft employee. Was going through the Container MCW. It was a awesome workshop. Kudos to the person who created it. I just found this small typo. There are couple of other things I wanted to highlight but did not find time to point them out. I went through the whole workshop. I will suggest some more minor changes once I get some time. thanks!

**Pull request merged**
